---
sources:
    - name: meter_source
      interval: 600
      meters:
          - "!*"
      sinks:
          - meter_sink
    - name: cpu_bill_source
      interval: 60
      meters:
          - "cpu"
      sinks:
          - cpu_bill_sink
    - name: memory_bill_source
      interval: 60
      meters:
          - "memory.usage"
      sinks:
          - meter_sink
    - name: disk_bill_source
      interval: 60
      meters:
          - "disk.read.bytes"
          - "disk.write.bytes"
      sinks:
          - disk_bill_sink
    - name: bandwidth_bill_source
      interval: 60
      meters:
          - "bandwidth"
      sinks:
          - meter_sink
    - name: es_network_source
      interval: 60
      meters:
           - "network.es.port.incoming.internal.bytes"
           - "network.es.port.incoming.external.bytes"
           - "network.es.port.outgoing.internal.bytes"
           - "network.es.port.outgoing.external.bytes"
           - "network.services.es.lb.incoming.bytes"
           - "network.services.es.lb.outgoing.bytes"
           - "network.services.es.lb.total.connections"
           - "network.services.es.lb.http.*"
      sinks:
          - meter_sink
sinks:
    - name: meter_sink
      transformers:
      publishers:
          - notifier://
    - name: cpu_bill_sink
      transformers:
          - name: "rate_of_change"
            parameters:
                target:
                    name: "cpu_util"
                    unit: "%"
                    type: "gauge"
                    scale: "100.0 / (10**9 * (resource_metadata.cpu_number or 1))"
      publishers:
          - notifier://
    - name: disk_bill_sink
      transformers:
          - name: "rate_of_change"
            parameters:
                source:
                    map_from:
                        name: "disk\\.(read|write)\\.bytes"
                        unit: "(B|request)"
                target:
                    map_to:
                        name: "disk.\\1.bytes.rate"
                        unit: "\\1/s"
                    type: "gauge"
      publishers:
          - notifier://
